// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../test/bootstrap.js', ['ssd.test.bootstrap'], ['ssd.test.config', 'ssd.test.core', 'ssd.test.event.all', 'ssd.test.helpers', 'ssd.test.user']);
goog.addDependency('../../../test/core.test.js', ['ssd.test.core'], []);
goog.addDependency('../../../test/events/events.test.js', ['ssd.test.event.all'], []);
goog.addDependency('../../../test/helpers/helpers.test.js', ['ssd.test.helpers'], []);
goog.addDependency('../../../test/modules/user/user.test.js', ['ssd.test.user'], []);
goog.addDependency('../../../test/structs/config.test.js', ['ssd.test.config'], []);
