// This file was autogenerated by calcdeps.py
goog.addDependency("../../../ss/helpers/date.core.js", ['ss.date'], ['goog.date', 'goog.date.DateTime']);
goog.addDependency("../../../ss/helpers/helpers.js", ['ss.helpers'], ['ss.date', 'goog.array', 'goog.object']);
goog.addDependency("../../../ss/helpers/helpers_test.js", [], ['ss.helpers', 'goog.testing.jsunit']);
